import Head from "next/head";
import {
  Box, Button, Flex, Heading, Text,
  Container,
  Stack,
  Image,
  Icon,
  IconButton,
  createIcon,
  IconProps,
  useColorModeValue,
} from "@chakra-ui/react";
import Link from "next/link";
import Navbar from "@/components/Navbar";
import AnimationData from '@/components/ok.json'
// @ts-ignore
import Lottie from 'react-lottie';

const defaultOptions = {
  loop: true,
  autoplay: true,
  animationData: AnimationData,
  rendererSettings: {
    preserveAspectRatio: "xMidYMid slice"
  }
};

export default function Home() {
  return (
    <>
      <Head>
        <title>PrescibeMe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Container maxW={'7xl'}>
          <Stack
            align={'center'}
            spacing={{ base: 8, md: 10 }}
            pt={{ base: 20, md: 10 }}
            direction={{ base: 'column', md: 'row' }}>
            <Stack flex={1} spacing={{ base: 5, md: 10 }}>
              <Heading
                lineHeight={1.1}
                fontWeight={600}
                fontSize={{ base: '3xl', sm: '4xl', lg: '6xl' }}>
                <Text
                  as={'span'}
                  position={'relative'}
                  color={'green.500'}
                  _after={{
                    content: "''",
                    width: 'full',
                    height: '30%',
                    position: 'absolute',
                    bottom: 1,
                    left: 0,  
                    zIndex: -1,
                  }}>
                  PrescribeMe
                </Text>
                <br />
                <Text as={'span'} color={'green.500'}>
                  
                </Text>
              </Heading>
              <Text color={'gray.500'}>
              Get hassle-free, convenient access to prescriptions with our online prescription website. Our platform connects you with licensed healthcare professionals who can diagnose and prescribe medications online.
              </Text>
              <Stack
                spacing={{ base: 4, sm: 6 }}
                direction={{ base: 'column', sm: 'row' }}>
                <Button
                  rounded={'full'}
                  size={'lg'}
                  fontWeight={'normal'}
                  px={6}
                  colorScheme={'green.500'}
                  bg={'green.500'}
                  _hover={{ bg: 'green.500' }}>
                  <Link href="/login">
                    Get started
                  </Link>
                </Button>
              </Stack>
            </Stack>
            <Flex
              flex={1}
              justify={'center'}
              align={'center'}
              position={'relative'}
              w={'full'}>

              <Box
                position={'relative'}
                height={'500px'}
                rounded={'2xl'}
                // boxShadow={'2xl'}
                width={'full'}
                overflow={'hidden'}>
                <IconButton
                  aria-label={'Play Button'}
                  variant={'ghost'}
                  _hover={{ bg: 'transparent' }}

                  size={'lg'}
                  color={'white'}
                  position={'absolute'}
                  left={'50%'}
                  top={'50%'}
                  transform={'translateX(-50%) translateY(-50%)'}
                />
                <Lottie
                  options={defaultOptions}
                  height={400}
                  width={400}
                />
              </Box>
            </Flex>
          </Stack>
        </Container>
      </main>
    </>
  );
}
