import Head from "next/head";
import { Box, Button, Flex, Heading, Text } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>E Prescibe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box mx="auto" maxW="5xl" pt={16}>
          <Heading size='2xl'>E-Prescribe</Heading>
          <Text mt={8} textColor="GrayText" maxW="400px">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda
            placeat voluptate odio dolorum voluptatem magni suscipit? Natus
            neque dolorem error, nam asperiores quasi sequi ad. Vel nam
            architecto numquam doloremque!
          </Text>

          <Flex mt={4} gap={4}>
            <Button colorScheme="green">Login</Button>
            <Button colorScheme="green" variant="outline">
              Singup
            </Button>
          </Flex>
        </Box>
      </main>
    </>
  );
}
